### ISSUE TITLE
[疑问]Nemo如何设置为中文

### ISSUE THREAD

**Issue by Fanccy315** [SR-MyStar/Hyprdots#1]
在Hyprland的env.conf中，我自行添加了`env=LANG,zh_CN.UTF-8`
但Nemo仍不是中文
![2024-01-10-07-55-18-window](https://github.com/SR-MyStar/Hyprdots/assets/95154395/9f395ab5-2147-4dc6-89c7-24a3a7574ed0)

**Comment by Buer-Nahida** [comment]
你/etc/locale.gen文件中把zh_CN.UTF-8 UTF-8取消注释并执行sudo locale-gen了吗，没有就照做一下再重启试试

**Comment by Buer-Nahida** [comment]
如果还是不行并且你不常用tty终端，尝试在/etc/locale.conf文件中写上LANG=zh_CN.UTF-8

**Comment by Fanccy315** [comment]
谢谢，已经解决了
安装`cinnamon-translations`即可
